name: appstitch_core
description: Appstitch's core package. Required for all Appstitch integrations
version: 2.0.2
homepage: https://appstitch.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.0
  encrypt: ^5.0.0-beta.1
  tuple: ^2.0.0
  crypto: ^3.0.0
  json_annotation: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.11.0
  json_serializable: ^4.0.0
